experiment_setup_parameters:
  'number_of_samples': 600
  'number_of_runs': 1
  'duration': 400
  'monitoring_samples': 400 
  'random_seed': 751
  'initialAs': 10
fixed_parameters_region_specific:
  populations:
    'IL': 12830632
  startdate:
    'IL': 2020-01-01
fixed_parameters_global:
sampled_parameters:
  'time_to_infectious':
    np.random: uniform
    function_kwargs: {'low': 3.4, 'high':4.5}
  'time_to_symptoms':
    np.random: uniform
    function_kwargs: {'low': 2.4, 'high': 3.5}
  'time_to_hospitalization':
    np.random: uniform
    function_kwargs: {'low':3, 'high':6}
  'time_to_critical':
    np.random: uniform
    function_kwargs: {'low':4, 'high':6}
  'time_to_death':
    np.random: uniform
    function_kwargs: {'low':4, 'high':6}
  ### DELAY BETWEEN ONSET OF SYMPTOMS AND BEING TESTED 
  'time_to_detection':
    np.random: uniform
    function_kwargs: {'low':2.0, 'high':2.0}
  'time_to_detection_As':
    np.random: uniform
    function_kwargs: {'low':1.0, 'high':6.0}
  'time_to_detection_Sym':
    np.random: uniform
    function_kwargs: {'low':7.0, 'high':7.0}
  'time_to_detection_Sys':
    np.random: uniform
    function_kwargs: {'low':2.0, 'high':2.0}
  ### RECOVERY TIMES 
  'recovery_time_asymp':
    np.random: uniform
    function_kwargs: {'low':7, 'high':10}
  'recovery_time_mild':
    np.random: uniform
    function_kwargs: {'low':9, 'high':9}
  'recovery_time_hosp':
    np.random: uniform
    function_kwargs: {'low':4, 'high':6}
  'recovery_time_crit':
    np.random: uniform
    function_kwargs: {'low':8, 'high':10}
  'fraction_symptomatic':
    np.random: uniform
    function_kwargs: {'low':0.5, 'high':0.7}
  'fraction_severe':
    np.random: uniform
    function_kwargs: {'low':0.06, 'high':0.1}
  'fraction_critical':
    np.random: uniform
    function_kwargs: {'low':0.20, 'high':0.35}
  'cfr': 
    np.random: uniform
    function_kwargs: {'low':0.01, 'high':0.03}
  'reduced_inf_of_det_cases':
    np.random: uniform
    function_kwargs: {'low':0, 'high':0.3}
  'd_Sys':
    np.random: uniform
    function_kwargs: {'low':0.00, 'high':0.0185} 
  'd_As':
    np.random: uniform
    function_kwargs: {'low':0, 'high':0}
  'd_P':
    np.random: uniform
    function_kwargs: {'low':0, 'high':0}
  'd_Sys_incr1':
    np.random: uniform
    function_kwargs: {'low':0.029, 'high':0.090}
  'd_Sys_incr2':
    np.random: uniform
    function_kwargs: {'low':0.090, 'high':0.192}
  'd_Sys_incr3':
    np.random: uniform
    function_kwargs: {'low':0.192, 'high':0.330}
  'd_Sys_incr4':
    np.random: uniform
    function_kwargs: {'low':0.330, 'high':0.450}
  'd_Sys_incr5':
    np.random: uniform
    function_kwargs: {'low':0.450, 'high':0.600}
  'd_Sys_incr6':
    np.random: uniform
    function_kwargs: {'low':0.600, 'high':0.800}
  'd_Sys_incr7':
    np.random: uniform
    function_kwargs: {'low':0.800, 'high':1.000}
  'fraction_critical_incr1':
    np.random: uniform
    function_kwargs: {'low':0.13, 'high':0.23}
  'fraction_critical_incr2':
    np.random: uniform
    function_kwargs: {'low':0.07, 'high':0.12}
  'fraction_critical_incr3':
    np.random: uniform
    function_kwargs: {'low':0.05, 'high':0.09}
intervention_parameters:
  'reopening_multiplier_4':
    np: logspace
    function_kwargs: {'start':-3, 'stop':-0.2, 'num' : 11}                                                                                                     
  'd_Sym_ct1':
    np.random: uniform
    function_kwargs: {'low':0.170, 'high':0.170}
  'change_testDelay_As_1':
    np: linspace
    function_kwargs: {'start':2, 'stop':7, 'num' : 1}
  'change_testDelay_Sym_1':
    np: linspace
    function_kwargs: {'start':2, 'stop':7, 'num' : 1}
  'reduced_inf_of_det_cases_ct1':
    np.random: uniform
    function_kwargs: {'low':0, 'high':1}
  'capacity_multiplier':
    np: linspace
    function_kwargs: {'start':0, 'stop':1, 'num': 1}
  'trigger_delay_days':
    np: linspace
    function_kwargs: {'start':1, 'stop':7, 'num':1}
time_parameters:
  'ki_multiplier_time_3a':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-03-12}
  'ki_multiplier_time_3b':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-03-17}
  'ki_multiplier_time_3c':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-03-21}
  'socialDistance_rollback_time':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-08-30}
  'gradual_reopening_time1':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-09-07}
  'gradual_reopening_time2':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-09-14} 
  'gradual_reopening_time3':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-09-21}
  'gradual_reopening_time4':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-09-28}
  'today':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-10-01}
  'detection_time_1':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-03-07}
  'detection_time_2':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-03-14}
  'detection_time_3':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-03-21}
  'detection_time_4':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-03-28} 
  'detection_time_5':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-04-04}
  'detection_time_6':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-04-18}
  'detection_time_7':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-06-01}
  'crit_time_1':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-04-01}
  'crit_time_2':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-05-01} 
  'crit_time_3':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-06-01}
  'd_Sym_change_time_1':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-03-15}
  'd_Sym_change_time_2':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-04-15}
  'd_Sym_change_time_3':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-05-01}
  'd_Sym_change_time_4':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-06-01}
  'd_Sym_change_time_5':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-07-01}
  'contact_tracing_start_1':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-08-30}
  'contact_tracing_stop1':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2022-05-30}
  'change_testDelay_time1':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-08-30}
  'cfr_time_1':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-06-01}
  'cfr_time_2':
    custom_function: DateToTimestep
    function_kwargs: {'dates': 2020-07-01}
fitted_parameters:
  Kis:
    'IL':
      np: linspace
      function_kwargs: {'start': 6.0e-8, 'stop': 9.0e-8, 'num': 1}