experiment_setup_parameters:
  age_bins:
    - EMS_1
    - EMS_2
    - EMS_3
    - EMS_4
    - EMS_5
    - EMS_6
    - EMS_7
    - EMS_8
    - EMS_9
    - EMS_10
    - EMS_11
fixed_parameters_region_specific:
  N:
    expand_by_age: True
    'IL': [688393,1269519, 581432, 676017, 424810, 760362, 791009, 1432193, 1012222, 2477754, 2716921]
fixed_parameters_global:
  initialAs:
    expand_by_age: True
    list: [10, 10, 10, 10,10, 9, 10, 10,10,10,10]
  speciesS:
    expand_by_age: True
    custom_function: subtract
    function_kwargs: {'x1': N, 'x2': initialAs}
sampled_parameters:
  d_Sym:  
    IL:
      expand_by_age: True
      np.random: uniform
      function_kwargs:
        - {'low': 0.0, 'high': 0.01}
        - {'low': 0.0, 'high': 0.01}
        - {'low': 0.0, 'high': 0.01}
        - {'low': 0.0, 'high': 0.01}
        - {'low': 0.0, 'high': 0.01}
        - {'low': 0.0, 'high': 0.01}
        - {'low': 0.0, 'high': 0.01}
        - {'low': 0.0, 'high': 0.01}
        - {'low': 0.0, 'high': 0.01}
        - {'low': 0.0, 'high': 0.01}
        - {'low': 0.0, 'high': 0.01}
  d_Sym_change1:
    IL:
      expand_by_age: True
      np.random: uniform
      function_kwargs:
        - {'low': 0.01, 'high': 0.08}
        - {'low': 0.01, 'high': 0.08}
        - {'low': 0.01, 'high': 0.08}
        - {'low': 0.01, 'high': 0.08}
        - {'low': 0.01, 'high': 0.08}
        - {'low': 0.01, 'high': 0.08}
        - {'low': 0.01, 'high': 0.08}
        - {'low': 0.01, 'high': 0.08}
        - {'low': 0.01, 'high': 0.08}
        - {'low': 0.01, 'high': 0.08}
        - {'low': 0.01, 'high': 0.08}
  d_Sym_change2:
    IL:
      expand_by_age: True
      np.random: uniform
      function_kwargs:
        - {'low': 0.05, 'high': 0.10}
        - {'low': 0.05, 'high': 0.10}
        - {'low': 0.05, 'high': 0.10}
        - {'low': 0.05, 'high': 0.10}
        - {'low': 0.05, 'high': 0.10}
        - {'low': 0.05, 'high': 0.10}
        - {'low': 0.05, 'high': 0.10}
        - {'low': 0.05, 'high': 0.10}
        - {'low': 0.05, 'high': 0.10}
        - {'low': 0.05, 'high': 0.10}
        - {'low': 0.05, 'high': 0.10}
  d_Sym_change3:
    IL:
      expand_by_age: True
      np.random: uniform
      function_kwargs:
        - {'low': 0.10, 'high': 0.20}
        - {'low': 0.10, 'high': 0.20}
        - {'low': 0.10, 'high': 0.20}
        - {'low': 0.10, 'high': 0.20}
        - {'low': 0.10, 'high': 0.20}
        - {'low': 0.10, 'high': 0.20}
        - {'low': 0.10, 'high': 0.20}
        - {'low': 0.10, 'high': 0.20}
        - {'low': 0.10, 'high': 0.20}
        - {'low': 0.10, 'high': 0.20}
        - {'low': 0.10, 'high': 0.20}
  d_Sym_change4:
    IL:
      expand_by_age: True
      np.random: uniform
      function_kwargs:
        - {'low': 0.10, 'high': 0.30}
        - {'low': 0.10, 'high': 0.30}
        - {'low': 0.10, 'high': 0.30}
        - {'low': 0.10, 'high': 0.30}
        - {'low': 0.10, 'high': 0.30}
        - {'low': 0.10, 'high': 0.30}
        - {'low': 0.10, 'high': 0.30}
        - {'low': 0.10, 'high': 0.30}
        - {'low': 0.10, 'high': 0.30}
        - {'low': 0.10, 'high': 0.30}
        - {'low': 0.10, 'high': 0.30}
  d_Sym_change5:
    IL:
      expand_by_age: True
      np.random: uniform
      function_kwargs:
        - {'low': 0.10, 'high': 0.40}
        - {'low': 0.10, 'high': 0.40}
        - {'low': 0.10, 'high': 0.40}
        - {'low': 0.10, 'high': 0.40}
        - {'low': 0.10, 'high': 0.40}
        - {'low': 0.10, 'high': 0.40}
        - {'low': 0.10, 'high': 0.40}
        - {'low': 0.10, 'high': 0.40}
        - {'low': 0.10, 'high': 0.40}
        - {'low': 0.10, 'high': 0.40}
        - {'low': 0.10, 'high': 0.40}